name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 7 * * *'  # Tous les jours à 7h UTC
  workflow_dispatch:      # Lancement manuel depuis GitHub

permissions:
  security-events: write
  contents: read

jobs:

  dependencies-analysis:
    name: Check Dependencies with OSV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v1

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv.sarif

  source-code-analysis:
    name: Static Analysis with Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep scan
        run: semgrep scan --config p/java --sarif > semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

