name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:

  dependencies-analysis:
    name: Check Dependencies with OSV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OSV Scanner
        run: |
          curl -LO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64
          chmod +x osv-scanner-linux-amd64
          sudo mv osv-scanner-linux-amd64 /usr/local/bin/osv-scanner

      - name: Run OSV Scanner
        id: osv-scan
        run: |
          osv-scanner --source-directory=. --format=sarif --output=osv.sarif || true
          if [ -s osv.sarif ]; then
            echo "sarif_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "sarif_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload SARIF report (if exists and not empty)
        if: steps.osv-scan.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv.sarif

  source-code-analysis:
    name: Static Analysis with Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep scan (extended rules)
        id: semgrep-scan
        run: |
          semgrep scan --config "p/java p/security-audit p/r2c-security-audit p/secrets" --sarif > semgrep.sarif || true
          if [ -s semgrep.sarif ]; then
            echo "sarif_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "sarif_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload SARIF report (if exists and not empty)
        if: steps.semgrep-scan.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

